addons:
  apt:
    packages:
    - aspell
    - aspell-en
    - python-pip
    - gcc
    - g++
    - gfortran
    - libblas3gf
    - libblas-dev
    - liblapack3gf
    - liblapack-dev
    - libatlas-base-dev
    - libxml2-dev
    - libxslt1-dev
    - python
    - python-matplotlib 
    - python-numpy 
    - python-scipy
    - python-sklearn
language: python
sudo: false
python:
  - "2.7"
virtualenv:
  system_site_packages: true
install:
  - pip install -r base-requirements.txt
  - pip install -r dev-requirements.txt
  - pip install scikit-learn==0.12.1
  - pip install -e git+https://github.com/edx/nltk.git@2.0.6#egg=nltk
  - travis_retry ./download-nltk-corpus.sh
script:  nosetests
