dist: xenial
language: python
python:
  - '3.8'
before_install:
  - sudo apt-get update
  - sudo xargs -a apt-packages.txt apt-get install --fix-missing
install:
  - pip install -r requirements/travis.txt
  - travis_retry ./download-nltk-corpus.sh
script:
  - make test
